//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_6_8.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Project
    {
        public int ID_Project { get; set; }
        [Required(ErrorMessage = "Tên không được để trống.")]
        public string Name_Project { get; set; }
        [Required(ErrorMessage = "Nơi thi công không được để trống.")]
        public string Detail_Project { get; set; }
        [Required(ErrorMessage = "Link hình ảnh không được để trống.")]
        public string Image_Project { get; set; }
        public string Type_Project { get; set; }
    }
}
